name: Issue Information
on:
    issues:
      types: [opened, edited, closed, deleted]
    issue_comment:
      types: [created, edited, deleted]
jobs:
    issue_information:
        runs-on: ubuntu-latest
        steps:
        - name: Display Issue Information
          run: echo "Issue Title==> ${{ toJson(github.event.issue.title) }} issue number is ${{ toJson(github.event.issue.number) }}"        
        - name: Display Issue Body
          run: echo "Issue Body==> ${{ toJson(github.event.issue.body) }}"
        - name: Display Json
          run: echo "Issue Json==> ${{ toJson(github.event) }}"